apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: durga-puja
type: Opaque
stringData:
  # RDS Connection
  MONGODB_URI: "postgresql://admin:password@rds-endpoint:5432/durgapuja"
  
  # Redis Connection
  REDIS_URL: "redis://:password@redis-endpoint:6379"
  
  # JWT Secret
  JWT_SECRET: "your-super-secure-jwt-secret-change-this"
  
  # Cloudinary
  CLOUDINARY_API_KEY: "your-api-key"
  CLOUDINARY_API_SECRET: "your-api-secret"
