[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "backend"
source = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"
