apiVersion: v1
kind: Namespace
metadata:
  name: durga-puja
  labels:
    name: durga-puja
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    environment: production
