name: Terraform Plan Preview

on:
  pull_request:
    paths:
      - 'infrastructure/terraform/**'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      working-directory: ./infrastructure/terraform
      run: terraform init
    
    - name: Terraform Plan
      working-directory: ./infrastructure/terraform
      run: |
        terraform plan -no-color > plan.txt
        cat plan.txt
      env:
        TF_VAR_mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
        TF_VAR_redis_password: ${{ secrets.REDIS_PASSWORD }}
    
    - name: Comment PR with Plan
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const plan = fs.readFileSync('infrastructure/terraform/plan.txt', 'utf8');
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Terraform Plan\n\`\`\`\n${plan}\n\`\`\``
          });
